const d = new Date();

export const FORM_DEFAULT_VALUES = {
  date: `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`,
  cashier_code: "",
  cashier_name: "",
  location_code: "",
  location_name: "",
  payment_method_code: "",
  payment_method_name: "",
  payment_type_code: "",
  payment_type_name: "",
  payment_mode_code: "",
  payment_mode_name: "",
  currency: "AED",
  vendor_code: "",
  user_id: "",
  purchase_order: "",
  pay_to: "employee",
  ap_invoice: "",
  pay_to_others: "",
  vat_percent: 0,
  employee_code: "",
  status: "y",
  remarks: "",
  attachments: "",
  items: [
    {
      division: "",
      department: "",
      product_line: "",
      gl_code: "",
      gl_name: "",
      description: "",
      total: 0,
      attachments: [],
    },
  ],
};
